version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules 
    environment:
      - PORT=5000
    # env_file:
    #   - ./.env


#  docker run -d -v ${pwd}:/app:ro -v /app/node_modules --env-file ./.env -p 5000:5000 --name node-app node-app-image