version: '3.8'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app 
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - MONGO_USER=Daniel
      - MONGO_PASSWORD=myPassword
      - SESSION_SECRET=secret
    command: npm run dev 
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Daniel
      - MONGO_INITDB_ROOT_PASSWORD=myPassword


    # persist the data during the development 